# Generated by Django 3.0 on 2020-01-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesblog',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gamesblog',
            name='install_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamesblog',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
