# Generated by Django 3.0 on 2020-01-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesblog', '0002_auto_20200110_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesblog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
