# Generated by Django 3.0 on 2020-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsblog', '0003_appsblog_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsblog',
            name='install_steps',
            field=models.TextField(blank=True),
        ),
    ]
