# Generated by Django 3.0 on 2020-01-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsblog', '0004_appsblog_install_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsblog',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
