# Generated by Django 3.0 on 2020-01-10 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsblog', '0008_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
