# Generated by Django 3.0 on 2020-01-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsblog', '0009_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsblog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
