# Generated by Django 3.0 on 2020-01-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorials',
            name='image',
        ),
        migrations.AddField(
            model_name='tutorials',
            name='iframe_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
